name: Test & Deploy Project
on: [workflow_dispatch]
jobs:
    # First Job: Test
    test:
        runs-on: ubuntu-latest
        steps:
        # ie First step: download code from reository
        -   name: Get code 
            uses: actions/checkout@v4
        # Second step: Install Node.js
        -   name: Install Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '18'
        # Third step: Install dependencies
        -   name: Install dependencies
            run: npm ci    
        
        # Fourth step: Run tests
        -   name: Run tests
            run: npm test

    # Second Job: Deploy
    deploy: 
        needs: [test]
        runs-on: ubuntu-latest       
        steps:
        # ie First step: download code from reository
        -   name: Get code 
            uses: actions/checkout@v4
            
        # Second step: Install Node.js
        -   name: Install Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '18'

        # Third step: Install dependencies
        -   name: Install dependencies
            run: npm ci  
            
        # Fourth step: Build project
        -   name: Build project
            run: npm run build