name: Exercise Workflow
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Set up Node.js
                uses: actions/setup-node@v3  
                with:
                    node-version: '18'
            -   name: Install dependencies
                run: npm ci
            -   name: Install linter 
                run: npm i eslint              
            -   name: Initialize lint config 
                run: npm init @eslint/config@latest -- --config eslint-config-xo
            -   name: Run linter
                run: npx eslint

    test:
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Set up Node.js
                uses: actions/setup-node@v3  
                with:
                    node-version: '18'
            -   name: Install dependencies
                run: npm ci
            -   name: Run tests
                run: npm test      
                
    build:
        runs-on: ubuntu-latest  
        needs: [test]
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Set up Node.js
                uses: actions/setup-node@v3  
                with:
                    node-version: '18'
            -   name: Install dependencies
                run: npm ci
            -   name: Build project
                run: npm run build          
